//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocioRegistro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SOCIOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CEDULA { get; set; }
        public byte[] FOTO { get; set; }
        public string DIRECCION { get; set; }
        public string NUMERO_CONTACTO { get; set; }
        public string SEXO { get; set; }
        public string EDAD { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string FAMILIARES { get; set; }
        public string TIPO_MEMBRESIA { get; set; }
        public string LUGAR_TRABAJO { get; set; }
        public string DIRECCION_OFICINA { get; set; }
        public string TEL_OFICINA { get; set; }
        public string ESTADO_MENBRESIA { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
    }
}
